language: python
sudo: required
dist: xenial
python:
  - "3.4"
env:
  - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe ORACLE_SID=XE OCI_LIB_DIR=/u01/app/oracle/product/11.2.0/xe/lib LD_LIBRARY_PATH=/u01/app/oracle/product/11.2.0/xe/lib
before_install:
  - wget https://raw.githubusercontent.com/Vincit/travis-oracledb-xe/master/accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
  - bash ./accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh

install:
  - pip install -r requirements.txt
  - pip install codecov
script: 
  - python manage.py makemigrations app
  - python manage.py migrate
  - coverage run manage.py test app --keepdb
  - coverage report
  - python query.py
  - codecov --token=7e44d6cb-5f46-4061-8545-013bd6e780cf 
notifications:
  email:
  - acekun141@gmail.com