# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-22 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfomationEnterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=500)),
                ('select', models.CharField(choices=[('Dưới 10 nhân viên', 'Dưới 10 nhân viên'), ('Từ 10-49 nhân viên', 'Từ 10-49 nhân viên'), ('Từ 50-99 nhân viên', 'Từ 50-99 nhân viên'), ('Từ 100-499 nhân viên', 'Từ 100-499 nhân viên'), ('Từ 500-1000 nhân viên', 'Từ 500-1000 nhân viên'), ('Trên 1000 nhân viên', 'Trên 1000 nhân viên')], max_length=100)),
                ('describe', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=200)),
                ('workplace', models.CharField(choices=[('Hà Nội', 'Hà Nội'), ('Hồ Chí Minh', 'Hồ Chí Minh'), ('Bình Dương', 'Bình Dương'), ('Bắc Ninh', 'Bắc Ninh'), ('Đồng Nai', 'Đồng Nai'), ('Hưng Yên', 'Hưng Yên'), ('Hải Dương', 'Hải Dương'), ('Đà Nẵng', 'Đà Nẵng'), ('Hải Phòng', 'Hải Phòng')], max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=100)),
                ('worktime', models.CharField(choices=[('Toàn thời gian', 'Toàn thời gian'), ('Bán thời gian', 'Bán thời gian'), ('Thực tập', 'Thực tập')], max_length=1)),
                ('sex', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Nam/Nữ', 'Nam/Nữ')], max_length=100)),
                ('exp', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=100)),
                ('deadline', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=100)),
                ('des_of_company', models.TextField(blank=True, max_length=255)),
                ('describe', models.TextField()),
                ('require', models.TextField()),
                ('benefit', models.TextField(default='')),
                ('skill', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.InfomationEnterprise')),
            ],
        ),
    ]
